services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/backend
    environment:
      - NODE_ENV=development
    networks:
      - music-review

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development
    networks:
      - music-review

networks:
  music-review:
    driver: bridge
