name: CI

on: [workflow_dispatch, push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Set up database environment
        working-directory: ./backend
        run: |
          echo "DATABASE_URL=file:$(pwd)/music-api-test.db\nTEST_DATABASE_URL=file:$(pwd)/music-api-test.db\nJWT_SECRET=MY-JWT-SECRET" > .env
          cat .env

      - name: Verify Prisma Configuration
        working-directory: ./backend
        run: npx prisma validate

      - name: Jest Run
        working-directory: ./backend
        env:
          DATABASE_URL: file:$(pwd)/music-api-test.db
          TEST_DATABASE_URL: file:$(pwd)/music-api-test.db
          JWT_SECRET: MY-JWT-SECRET
        run: npm test
