name: CI

on: [workflow_dispatch, push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 23.4.0
        uses: actions/setup-node@v4
        with:
          node-version: '23.4.0'
          cache: 'npm'
      - run: npm ci

      - name: Jest Run
        run: npm test